# Use an official Python runtime as a parent image
FROM python:3

# Set work directory
WORKDIR /djangoapprunner/app

# Install dependencies
COPY /requirements.txt  /djangoapprunner/app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /djangoapprunner/app/

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]